config/routes.rb
MetadocApp::Application.routes.draw do
  
  
  get 'upload', :controller => 'documents', :action => 'upload'
  post 'upload', :controller => 'documents', :action => 'getuuid'
  
  resources :users

  resources :documents

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :uuid
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
require 'rest-client'
require 'json'

class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
    @api_token = "hNX6fJnDQogYCajrt1KM8Tzy"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])
    @doc_uuid = @document.uuid
    @api_token = "hNX6fJnDQogYCajrt1KM8Tzy"
    
    @result = JSON.parse(RestClient.post "https://crocodoc.com/api/v2/session/create", "token=#{@api_token}&uuid=#{@doc_uuid}&editable=true&user=1,Jamie")
    @session = @result["session"]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])
    @api_token = "hNX6fJnDQogYCajrt1KM8Tzy"

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
  
  def upload
    @document = Document.new


    # RestClient.post 'https://crocodoc.com/api/v2/document/upload/token=hNX6fJnDQogYCajrt1KM8Tzy', :file =>  File.new(document, 'rb')
    
    # RestClient.post "https://crocodoc.com/api/v2/document/upload/", "token=#{params[:token]}&file=#{params[:document].original_filename}"
    
  end
  
  def getuuid
        @document = Document.new 
        @result = JSON.parse(RestClient.post "https://crocodoc.com/api/v2/document/upload?", :token => "hNX6fJnDQogYCajrt1KM8Tzy", :url => "#{params[:url]}")
        @document.uuid = @result["uuid"]
        @document.save
        redirect_to documents_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br />
    <%= f.text_field :uuid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/_uploadform.html.erb
<%= form_tag("upload", :controller => "documents", :action => "getuuid") do %>
  <%= label_tag(:url, "Paste your document URL below.") %>
  <%= text_field_tag(:url) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/getuuid.html.erb
<%= @result %>

app/views/documents/index.html.erb
<div id="subheader">
	<div class="inner">
		<div class="container">
			<h1>METADOCS: Your Documents</h1>
		</div> <!-- /.container -->
	</div> <!-- /inner -->
</div> <!-- /subheader -->
<br />
<p><%= link_to 'New Document', "upload" %></p>

<% @documents.each do |document| %>
  <tr>
	<td><a href="/documents/<%=document.id%>"><img src="https://crocodoc.com/api/v2/download/thumbnail?token=<%= @api_token %>&uuid=<%= document.uuid %>&size=300x300"></a></td>
<td><%= link_to 'Delete', document, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<!-- <%= render 'uploadform' %> -->

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

	<%= link_to 'Back', documents_path %>
<div align=center>

	<p><a href="https://crocodoc.com/api/v2/download/document?token=<%= @api_token %>&uuid=<%= @document.uuid %>">Download this file</a></p>
<iframe src="https://crocodoc.com/view/<%= @session %>" width="75%"
height="700px" name="youriframe" frameborder="1" vspace="0" hspace="0"
marginwidth="0" marginheight="0" scrolling="yes" noresize></iframe>
</div>

app/views/documents/upload.html.erb
<h1>Upload a new document</h1>


<%= render 'uploadform' %>

<%= link_to 'Back', documents_path %>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">

			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>

			<!-- <a brand href="./">
							MetaDocs				
						</a>	 -->		

			<div class="nav-collapse">
				<ul class="nav pull-right">
					
				</ul>

			</div><!--/.nav-collapse -->	

		</div> <!-- /container -->

	</div> <!-- /navbar-inner -->

</div> <!-- /navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MetadocApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>


  

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>